'use strict';
const KEY='suntech-ecommerce-meeting-v1';
const STATUS=['待更新','未开始','进行中','待核验','已完成','受阻','暂缓'];
const CATEGORIES=['会前准备','客户经营','两店整合','渠道工具','会议跟进'];
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>globalThis.crypto?.randomUUID?.()||'r'+Date.now().toString(36)+Math.random().toString(36).slice(2);
const direction={id:'merger-direction',title:'确定两店整合方向',category:'两店整合',priority:'P0',owner:'',due:'',status:'已完成',evidence:'已确认：玄甲店铺作为主店，美安士店铺转移至玄甲店铺。',blocker:''};
const initialTasks=[
['会前准备','重做重点客户总表','列清客户经营模式、已有合作、机会依据、下一步动作和负责人。'],
['客户经营','准备熟悉客户的深入案例','建议每位业务员先选3个真实熟悉客户；材料可回查，推测单列。'],
['客户经营','完成一次针对性客户跟进','保存实际沟通内容、切入理由、客户反馈和后续动作。'],
['客户经营','梳理存量客户并确定优先级','形成潜力客户清单和研究进度；优先级有具体判断依据。'],
['两店整合','核实美安士转入玄甲的可行处理方式','确认客户、产品、历史记录、合同费用及平台限制，不假定评价或权重可直接转移。'],
['两店整合','备份美安士店铺相关业务资料','核对客户、询盘、产品、订单及售后资料的授权导出范围、完整性和保存位置。'],
['两店整合','落实客户承接与跟进负责人','建立客户对应和负责人清单；客户沟通与未完承诺有人继续负责。'],
['两店整合','整理产品并承接到玄甲店铺','建立SKU对应、去重和资料核对清单；确认适用上架规则后处理。'],
['两店整合','核对未完订单、回款与售后','逐项明确履约、付款、客户承诺及售后归口，不能因转移中断。'],
['两店整合','调整玄甲店铺推广与预算安排','在规则及费用确认后制定投流、关键词和产品推广调整方案。'],
['两店整合','完成转移验收并确认美安士后续处理','核对玄甲承接结果及遗留事项；关店或合同终止另行确认。'],
['渠道工具','盘点付费获客工具的实际使用与效果','核对账单周期、已用功能、有效线索、跟进和成交；提出继续或调整建议。'],
['渠道工具','准备一次自主开发客户演示','从公开来源寻找目标客户，展示筛选依据、研究和具体沟通切入点。'],
['渠道工具','让同事共同使用Accio Work完成任务','用真实客户或运营任务演示，另一位同事能独立复现并解释检查方法。'],
['会前准备','核对上次安排的完成情况','逐项补充状态、负责人、完成依据或卡点，不把待更新当作未完成。'],
['会议跟进','把本次决定转成下一步动作','每项行动列负责人、期限、成果及需要的协助。'],
['会议跟进','复盘任务推进与客户反馈','下次先核对前次行动、客户反应、整合进度及待决定事项。']
];
function seed(){return {version:1,tasks:[{...direction},...initialTasks.map((r,i)=>({id:'task-'+(i+1),category:r[0],title:r[1],criteria:r[2],priority:i<11?'P0':'P1',owner:'',due:'',status:'待更新',evidence:'',blocker:''}))],customers:[],channels:[],minutes:{focus:'',decisions:'',support:'',next:''}}}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500)}
let storageOK=true;
function text(v,max=6000){if(typeof v!=='string')return '';return v.slice(0,max)}
function date(v){if(!v)return '';if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v+'T00:00:00Z'))||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)throw Error('日期格式不正确');return v}
function numeric(v,integer=false){if(v===null||v===undefined||v==='')return null;const n=Number(v);if(!Number.isFinite(n)||n<0||(integer&&!Number.isInteger(n)))throw Error('金额和数量必须为有效非负数');return n}
function validate(raw){
 if(!raw||raw.version!==1||!Array.isArray(raw.tasks)||!Array.isArray(raw.customers)||!Array.isArray(raw.channels))throw Error('文件不是此工作台导出的数据');
 if([raw.tasks,raw.customers,raw.channels].some(a=>a.length>500))throw Error('记录数量超过上限');
 const s={version:1,tasks:[],customers:[],channels:[],minutes:{}};
 const seen=new Set();const getId=v=>{const k=text(v,120);if(!k||seen.has(k))throw Error('记录编号缺失或重复');seen.add(k);return k};
 s.tasks=raw.tasks.map(t=>{if(!t||typeof t!=='object')throw Error('待办格式不正确');const k=getId(t.id);if(k===direction.id)return {...direction,owner:text(t.owner,100)};if(!CATEGORIES.includes(t.category)||!STATUS.includes(t.status)||!['P0','P1','P2'].includes(t.priority)||!text(t.title,200).trim())throw Error('待办内容或状态不正确');return {id:k,title:text(t.title,200),category:t.category,priority:t.priority,owner:text(t.owner,100),due:date(t.due),status:t.status,criteria:text(t.criteria),evidence:text(t.evidence),blocker:text(t.blocker)}});
 if(!s.tasks.some(t=>t.id===direction.id))s.tasks.unshift({...direction});
 const customerKeys=['name','country','website','owner','model','cooperation','opportunity','action','feedback','next'];
 s.customers=raw.customers.map(r=>{if(!r||!text(r.name,160).trim())throw Error('客户名称缺失');const c={id:getId(r.id),due:date(r.due)};customerKeys.forEach(k=>c[k]=text(r[k],['name','country','website','owner'].includes(k)?300:6000));return c});
 s.channels=raw.channels.map(r=>{if(!r||!text(r.name,160).trim())throw Error('渠道名称缺失');const c={id:getId(r.id),name:text(r.name,160),period:text(r.period,160),currency:['CNY','USD','EUR'].includes(r.currency)?r.currency:'CNY',spend:numeric(r.spend),leads:numeric(r.leads,true),quotes:numeric(r.quotes,true),deals:numeric(r.deals,true),usage:text(r.usage),evidence:text(r.evidence),recommendation:text(r.recommendation),owner:text(r.owner,100)};if([c.spend,c.leads,c.quotes,c.deals].some(v=>v!==null)&&!c.period.trim())throw Error('有渠道数据时必须填写统计期');return c});
 for(const k of ['focus','decisions','support','next'])s.minutes[k]=text(raw.minutes?.[k]);return s;
}
let state;
try{const saved=localStorage.getItem(KEY);state=saved?validate(JSON.parse(saved)):seed()}catch(e){state=seed();storageOK=false;$('#storageInfo').textContent='本地记录暂时无法读取，当前显示初始清单。请保留原数据并使用导入恢复，新的修改可导出备份。'}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;$('#saveStatus').textContent='已保存到当前浏览器'}catch(e){storageOK=false;$('#saveStatus').textContent='未能本地保存';$('#storageInfo').textContent='浏览器暂时无法保存修改，请使用“导出数据”保存文件，避免关闭后丢失。'} }
function today(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function overdue(t){return t.due&&t.due<today()&&!['已完成','暂缓'].includes(t.status)}
function badge(t){const c=t==='已完成'?'done':t==='受阻'?'blocked':['待更新','待核验'].includes(t)?'pending':'';return `<span class="badge ${c}">${esc(t)}</span>`}
function stats(target){const ts=state.tasks,done=ts.filter(t=>t.status==='已完成').length,active=ts.filter(t=>['进行中','待核验'].includes(t.status)).length,unknown=ts.filter(t=>t.status==='待更新').length,stuck=ts.filter(t=>t.status==='受阻').length;$(target).innerHTML=[['全部待办',ts.length,''],['已标完成',done,Math.round(done/ts.length*100)+'% 手动状态'],['推进中 / 待核验',active,''],['待更新',unknown,'实际进度待补充'],['受阻',stuck,ts.filter(overdue).length+' 项期限已过']].map(([label,n,extra])=>`<div class="stat"><span>${label}</span><strong>${n}</strong><small>${extra||'&nbsp;'}</small></div>`).join('')}
const taskGuidance={
'task-1':['会前：把原表改成一张简明总表，至少列客户、经营方式、合作产品、潜在机会和下一步。','老板会问：这张表能不能看出我们重点推进谁？','03:18–04:19'],
'task-2':['会前：准备最熟悉客户的官网、合作和沟通资料，能讲透经营模式与拓展理由。','老板会问：为什么只合作这些产品，还可以怎样扩大合作？','01:37–02:39 / 07:19–07:58'],
'task-3':['会前：对重点客户做一次有针对性的跟进，保留发出材料与反馈。','老板会问：你的内容凭什么能引起客户兴趣？下一步怎么调整？','04:57–05:16 / 24:02–25:02'],
'task-4':['按录音要求，9月底完成客户基础分析，筛出有潜力且值得重点推进的对象。','会上说清：梳理到哪一步、优先客户是谁、剩下怎么完成。','20:41–23:02'],
'task-5':['核实平台允许的处理方式、数据范围与合同费用，列出哪些能做、哪些需人工承接。','这项是整合执行拆解，不把方向确定等同于自动迁移能力。','整合要求17:23–19:09'],
'task-6':['备份和核对美安士客户、询盘、产品、订单与售后记录，说明保存位置。','会上说清：备份了哪些，哪些仍无法取得，怎样保证后续能查。','整合实施建议'],
'task-7':['列清在谈、成交和售后客户的承接人，保留历史沟通和未完承诺。','老板会问：客户转过去后由谁继续跟，会不会断掉？','17:43–18:24'],
'task-8':['整理两店产品对应关系；确定玄甲优先承接哪些产品，核对参数、图片与价格。','会上说清：已处理哪些、还剩哪些、怎样避免重复和错资料。','整合实施建议'],
'task-9':['列出未交付、未回款和售后事项，逐项明确原责任与承接人。','会上说清：有哪些遗留业务，转移后怎样继续处理。','整合实施建议'],
'task-10':['按有效客户与成交表现提出玄甲推广产品和预算调整建议。','老板会问：为什么这样集中，依据是询盘便宜还是实际能成交？','16:00–17:23 / 21:23–21:43'],
'task-11':['核对玄甲承接结果与遗留事项，再确认美安士入口、合同的后续处理。','此项只有实际转移验收完成后才能标完成，方向确定不算。','整合实施建议'],
'task-12':['查小满/OKKI等已购服务的套餐、使用和真实产出，主动向服务方核实问题。','老板会问：花了钱为什么没效果？你建议继续、调整还是暂停？','12:37–13:58 / 31:02–33:41'],
'task-13':['准备Google、地图、LinkedIn等自主开发案例，现场展示从找到客户到形成切入点。','老板要看实际操作，以及你判断客户是否适合的依据。','09:41–10:41 / 12:18–12:59'],
'task-14':['由同事独立用Accio Work完成一个真实客户或运营任务，并解释检查方法。','老板要求部门共同使用，不能只有你一个人会。','33:41–34:43 / 49:11–50:11'],
'task-15':['逐项口头回应上次安排：已完成什么、没完成卡在哪里、下一步是什么。','会议先检查落实，不重复讲同一个计划。','10:41–12:18'],
'task-16':['会中口头确认负责人、动作、期限、完成依据和支持需求，录音后再补详细记录。','无需在会上逐字录入，本页只标状态。','10:41–12:18'],
'task-17':['下次复盘既看业绩数字，也看制定的客户推进和整合动作是否落实。','数字是结果，还要说明动作与反馈发生了什么变化。','25:21–26:25']
};
const taskAgenda={"task-1": ["形成简明客户总表，包含客户信息、经营模式、合作产品、潜在机会与后续行动。", "明确重点客户及推进优先级。"], "task-2": ["梳理重点客户官网、合作情况与沟通记录，分析经营模式和合作拓展空间。", "合作机会需有业务依据，未核实信息单列。"], "task-3": ["开展针对性客户跟进，保留沟通材料及反馈，调整后续动作。", "记录客户反应、推进结果和下一步。"], "task-4": ["9月底完成存量客户基础分析，筛选具备合作潜力的重点对象。", "明确已完成范围、剩余工作与完成计划。"], "task-5": ["核实美安士转入玄甲的平台规则、数据范围和合同费用。", "确定可执行的转移与人工承接方式。"], "task-6": ["备份并核对美安士客户、询盘、产品、订单及售后记录。", "确认数据完整性、保存位置与待补资料。"], "task-7": ["落实在谈、成交及售后客户的承接负责人，保留沟通与未完承诺。", "确保客户跟进和服务连续。"], "task-8": ["建立两店产品对应关系，核对参数、图片、价格并处理重复项。", "明确玄甲优先承接产品与剩余处理范围。"], "task-9": ["逐项核对未交付订单、未回款及售后事项。", "明确处理责任、客户承诺和后续节点。"], "task-10": ["结合有效客户与成交表现，调整玄甲推广产品、关键词和预算。", "记录调整依据及后续效果检查口径。"], "task-11": ["验收玄甲承接结果与遗留事项，确认美安士入口及合同后续安排。", "转移验收与后续店铺处理分别确认。"], "task-12": ["核对已购获客服务的套餐、费用、功能使用及客户产出。", "形成继续使用、优化或暂停的建议与依据。"], "task-13": ["验证公开渠道自主开发流程，完成目标筛选、客户研究与合作切入点分析。", "明确来源、业务匹配和后续开发动作。"], "task-14": ["推动部门人员独立使用Accio Work完成客户研究或运营任务。", "输出可核对、步骤可复用。"], "task-15": ["核对前次任务的完成结果、未完成原因与后续计划。", "进度与实际成果保持一致。"], "task-16": ["将本次确认事项形成后续行动。", "明确主责人、工作内容、期限、检查依据与协助需求。"], "task-17": ["复盘客户反馈、店铺整合及各项经营动作的执行情况。", "结合结果与过程调整下一阶段计划。"]};
function controls(t){if(t.id===direction.id)return '<span class="badge done">方向已确定</span>';return '<div class="quick-status">'+[['未开始','未完成'],['进行中','进行中'],['已完成','已完成'],['受阻','需协助']].map(([v,l])=>`<button data-task-status="${v}" data-task-id="${esc(t.id)}" class="${t.status===v?'selected':''}" aria-pressed="${t.status===v}">${l}</button>`).join('')+`<select aria-label="${esc(t.title)}的状态" data-status-select="${esc(t.id)}">${STATUS.map(v=>`<option ${v===t.status?'selected':''}>${v}</option>`).join('')}</select></div>`}
function taskTable(tasks){if(!tasks.length)return '<div class="empty">没有符合条件的事项。</div>';return '<div class="table-wrap"><table><thead><tr><th>工作事项与推进内容</th><th>执行状态</th></tr></thead><tbody>'+tasks.map(t=>{const g=taskGuidance[t.id],a=taskAgenda[t.id];return `<tr><td><span class="task-title">${esc(t.title)}</span><small>${esc(t.category)}${g?'<span class="presenter-only"> · 依据 '+esc(g[2])+'</span>':''}</small>${a?`<p class="task-guidance">${esc(a[0])}</p><p class="boss-ask">${esc(a[1])}</p>${g?`<div class="presenter-only"><p>${esc(g[0])}</p><p>${esc(g[1])}</p></div>`:''}`:(t.criteria?`<p class="task-guidance">${esc(t.criteria)}</p>`:'')}${t.owner||t.due?`<small>已有记录：${esc(t.owner||'负责人待补')} / ${esc(t.due||'期限待补')}</small>`:''}${t.evidence?`<small>已有进展：${esc(t.evidence)}</small>`:''}${t.blocker?`<small>卡点：${esc(t.blocker)}</small>`:''}${overdue(t)?'<span class="overdue">原期限已过，请核对状态</span>':''}</td><td class="status-cell">${badge(t.status)}${controls(t)}${t.id!==direction.id?`<button class="link-button" data-edit="task" data-id="${esc(t.id)}">选填详情</button>`:''}</td></tr>`}).join('')+'</tbody></table></div>'}
function renderTopics(){document.querySelectorAll('[data-topic-task]').forEach(el=>{const t=state.tasks.find(t=>t.id===el.dataset.topicTask);el.innerHTML=t?`<div class="topic-label"><strong>${esc(t.title)}</strong>${badge(t.status)}</div>${controls(t)}`:''})}
function setQuickStatus(taskId,status){if(!STATUS.includes(status)||taskId===direction.id)return;const t=state.tasks.find(t=>t.id===taskId);if(!t)return;t.status=status;save();renderTasks();toast(storageOK?'状态已保存。':'状态已更新，请导出备份。')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-task-status]');if(b)setQuickStatus(b.dataset.taskId,b.dataset.taskStatus)});
document.addEventListener('change',e=>{if(e.target.matches('[data-status-select]'))setQuickStatus(e.target.dataset.statusSelect,e.target.value)});
function renderTasks(){const q=$('#taskSearch').value.trim().toLowerCase(),cat=$('#categoryFilter').value,status=$('#statusFilter').value;const list=state.tasks.filter(t=>(!cat||t.category===cat)&&(!status||t.status===status)&&(!q||[t.title,t.owner,t.criteria,t.evidence,t.blocker].join(' ').toLowerCase().includes(q)));$('#taskTable').innerHTML=taskTable(list);const merger=state.tasks.filter(t=>t.category==='两店整合');$('#mergerTable').innerHTML=taskTable(merger);$('#mergerCount').textContent=`已完成 ${merger.filter(t=>t.status==='已完成').length} / ${merger.length} 项`;$('#nextTasks').innerHTML=taskTable(state.tasks.filter(t=>t.status!=='已完成'&&t.status!=='暂缓').sort((a,b)=>a.priority.localeCompare(b.priority)).slice(0,6));stats('#overviewStats');stats('#taskStats');renderTopics()}
function fact(label,value){return `<div><h3>${label}</h3><p>${esc(value||'待补充')}</p></div>`}
function renderCustomers(){$('#customerList').innerHTML=state.customers.length?state.customers.map(c=>`<article class="card customer-card"><div class="record-head"><div style="flex:1"><h2>${esc(c.name)}</h2><div class="record-meta">${esc(c.country||'国家待补')} · 负责人 ${esc(c.owner||'待指定')} · 下次跟进 ${esc(c.due||'待定')}</div><div class="record-meta">${esc(c.website||'官网 / 来源待补充')}</div></div><button data-edit="customer" data-id="${esc(c.id)}">编辑案例</button></div><div class="record-grid">${fact('客户经营与服务对象',c.model)}${fact('现有合作',c.cooperation)}${fact('合作机会与依据',c.opportunity)}${fact('已执行的动作',c.action)}${fact('客户反馈',c.feedback)}${fact('下一步与需要的支持',c.next)}</div></article>`).join(''):'<div class="empty">暂无已保存客户案例。</div>'}
function metric(n){return n===null?'待补':n.toLocaleString('zh-CN',{maximumFractionDigits:2})}
function renderChannels(){$('#channelList').innerHTML=state.channels.length?state.channels.map(c=>{const cpl=c.spend!==null&&c.leads!==null?(c.leads>0?(c.spend/c.leads).toLocaleString('zh-CN',{maximumFractionDigits:2})+' '+c.currency:'有效线索为0，暂不计算'):'数据待补';return `<article class="card customer-card"><div class="record-head"><div style="flex:1"><h2>${esc(c.name)}</h2><div class="record-meta">${esc(c.period||'统计期待补充')} · 负责人 ${esc(c.owner||'待指定')}</div></div><button data-edit="channel" data-id="${esc(c.id)}">更新复盘</button></div><div class="metric-row"><span>投入 <b>${metric(c.spend)} ${esc(c.currency)}</b></span><span>有效线索 <b>${metric(c.leads)}</b></span><span>报价客户 <b>${metric(c.quotes)}</b></span><span>成交客户 <b>${metric(c.deals)}</b></span><span>有效线索成本 <b>${esc(cpl)}</b></span></div><div class="record-grid">${fact('实际使用与效果',c.usage)}${fact('数据来源及统计口径',c.evidence)}${fact('调整建议与下一步',c.recommendation)}</div></article>`}).join(''):'<div class="empty">添加实际使用的渠道或付费工具，例如国际站推广、已购获客服务、自主开发渠道。金额与结果请按真实记录填写。</div>'}
function render(){renderTasks();renderCustomers();renderChannels();for(const el of document.querySelectorAll('[data-minute]'))if(document.activeElement!==el)el.value=state.minutes[el.dataset.minute]}
$('#categoryFilter').innerHTML='<option value="">全部分类</option>'+CATEGORIES.map(c=>`<option>${c}</option>`).join('');$('#statusFilter').innerHTML='<option value="">全部状态</option>'+STATUS.map(c=>`<option>${c}</option>`).join('');$('#taskSearch').oninput=renderTasks;$('#categoryFilter').onchange=renderTasks;$('#statusFilter').onchange=renderTasks;

let editing=null;
const field=(name,label,value='',opts={})=>`<label class="${opts.wide?'wide':''}">${label}${opts.area?`<textarea name="${name}" maxlength="6000" ${opts.required?'required':''}>${esc(value)}</textarea>`:opts.options?`<select name="${name}">${opts.options.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`:`<input name="${name}" type="${opts.type||'text'}" value="${esc(value??'')}" ${opts.type==='number'?'min="0" step="'+(opts.integer?'1':'any')+'"':'maxlength="300"'} ${opts.required?'required':''}>`}</label>`;
function openEditor(kind,recordId){const arr=state[kind==='task'?'tasks':kind==='customer'?'customers':'channels'];const r=arr.find(x=>x.id===recordId)||{};if(r.id===direction.id)return;editing={kind,id:r.id||null};$('#editorTitle').textContent=(r.id?'编辑':'新增')+({task:'待办事项',customer:'客户案例',channel:'渠道复盘'}[kind]);let html='';
 if(kind==='task')html=field('title','事项名称',r.title,{wide:true,required:true})+field('category','分类',r.category||'会议跟进',{options:CATEGORIES})+field('priority','优先级',r.priority||'P1',{options:['P0','P1','P2']})+field('owner','负责人',r.owner)+field('due','截止日期',r.due,{type:'date'})+field('status','实际状态',r.status||'待更新',{options:STATUS})+'<div class="hint">P0为优先处理。未确认实际进度时保留“待更新”。</div>'+field('criteria','完成标准',r.criteria,{area:true,wide:true})+field('evidence','完成依据 / 当前进展（选填，可待录音整理）',r.evidence,{area:true,wide:true})+field('blocker','卡点与需要的协助',r.blocker,{area:true,wide:true});
 if(kind==='customer')html=field('name','客户名称',r.name,{required:true})+field('country','国家 / 地区',r.country)+field('website','官网或资料来源',r.website,{wide:true})+field('owner','负责人',r.owner)+field('due','下次跟进日期',r.due,{type:'date'})+field('model','客户如何经营、卖给谁',r.model,{area:true,wide:true})+field('cooperation','现有合作与原因',r.cooperation,{area:true,wide:true})+field('opportunity','合作机会、依据和待验证判断',r.opportunity,{area:true,wide:true})+field('action','实际执行了什么',r.action,{area:true,wide:true})+field('feedback','客户反馈',r.feedback,{area:true,wide:true})+field('next','下一步与需要的支持',r.next,{area:true,wide:true});
 if(kind==='channel')html=field('name','渠道 / 工具名称',r.name,{required:true})+field('period','统计期',r.period)+field('currency','币种',r.currency||'CNY',{options:['CNY','USD','EUR']})+field('spend','投入金额（未知留空）',r.spend,{type:'number'})+field('leads','有效线索数（未知留空）',r.leads,{type:'number',integer:true})+field('quotes','报价客户数',r.quotes,{type:'number',integer:true})+field('deals','成交客户数',r.deals,{type:'number',integer:true})+field('owner','负责人',r.owner)+field('usage','已用功能、频次与实际产出',r.usage,{area:true,wide:true})+field('evidence','数据来源与有效线索定义',r.evidence,{area:true,wide:true})+field('recommendation','继续 / 调整 / 暂停的建议及下一步',r.recommendation,{area:true,wide:true});
 if(kind==='task'){const cut=html.indexOf('<label',html.indexOf('</label>')+8);html=html.slice(0,cut)+'<details class="wide optional"><summary>负责人、期限及说明（选填）</summary><div class="fields">'+html.slice(cut)+'</div></details>';}$('#editorFields').innerHTML='<div class="fields">'+html+'</div>';$('#deleteRecord').hidden=!r.id;const host=$('.page.active');host.insertBefore($('#editor'),host.querySelector('.lead').nextSibling);$('#editor').hidden=false;$('#editor').scrollIntoView({block:'nearest'});}
$('#closeEditor').onclick=$('#cancelEditor').onclick=()=>($('#editor').hidden=true);
$('#editorForm').onsubmit=e=>{e.preventDefault();try{const r=Object.fromEntries(new FormData(e.target));r.id=editing.id||id();const key=editing.kind==='task'?'tasks':editing.kind==='customer'?'customers':'channels';const copy=JSON.parse(JSON.stringify(state));const idx=copy[key].findIndex(t=>t.id===r.id);if(idx>=0)copy[key][idx]=r;else copy[key].push(r);state=validate(copy);save();render();($('#editor').hidden=true);toast(storageOK?'已保存':'已更新，请导出备份')}catch(err){toast(err.message)}};
$('#deleteRecord').onclick=()=>{if(!editing?.id||!confirm('确定删除这条记录？删除前可先导出备份。'))return;const key=editing.kind==='task'?'tasks':editing.kind==='customer'?'customers':'channels';state[key]=state[key].filter(r=>r.id!==editing.id);save();render();($('#editor').hidden=true);toast('已删除记录')};
document.addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)openEditor(b.dataset.edit,b.dataset.id);const g=e.target.closest('[data-go]');if(g)go(pages.findIndex(p=>p.id===g.dataset.go))});
$('#addTask').onclick=$('#addTaskFromMinutes').onclick=()=>openEditor('task');$('#addCustomer').onclick=()=>openEditor('customer');$('#addChannel').onclick=()=>openEditor('channel');
document.querySelectorAll('[data-minute]').forEach(el=>el.oninput=()=>{state.minutes[el.dataset.minute]=el.value.slice(0,6000);save()});

function download(content,type,filename){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#exportBtn').onclick=()=>download(JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2),'application/json','电商会议数据-'+today()+'.json');
$('#importBtn').onclick=()=>$('#importFile').click();
$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>4*1024*1024)throw Error('文件过大，请选择本工作台导出的JSON文件');const incoming=validate(JSON.parse(await f.text()));if(!confirm(`导入将替换当前浏览器记录（${incoming.tasks.length}项待办、${incoming.customers.length}个客户、${incoming.channels.length}项渠道）。建议先导出当前数据。确定导入？`))return;state=incoming;save();render();toast('已导入数据')}catch(err){toast('导入失败：'+err.message)}finally{e.target.value=''}};
$('#downloadMinutes').onclick=()=>{let md='# 电商部会议记录\n\n两店整合方向：玄甲店铺作为主店，美安士店铺转移至玄甲店铺。\n\n';for(const [k,label] of [['focus','讨论重点'],['decisions','已确认决定'],['support','需要协调或决定'],['next','下次检查']])md+='## '+label+'\n\n'+(state.minutes[k]||'待补充')+'\n\n';md+='## 待办情况\n\n';for(const t of state.tasks)md+=`- [${t.status==='已完成'?'x':' '}] ${t.title}（${t.status}；负责人：${t.owner||'待指定'}；期限：${t.due||'待定'}）\n  完成依据：${t.evidence||'待补充'}\n${t.blocker?'  卡点：'+t.blocker+'\n':''}`;md+='\n## 客户案例\n\n';for(const c of state.customers)md+=`### ${c.name}\n\n负责人：${c.owner||'待指定'}\n\n经营：${c.model}\n\n合作：${c.cooperation}\n\n机会与依据：${c.opportunity}\n\n动作：${c.action}\n\n反馈：${c.feedback}\n\n下一步：${c.next}\n\n`;download(md,'text/markdown;charset=utf-8','电商部会议纪要-'+today()+'.md')};
const pages=[...document.querySelectorAll('.page')];let current=0;
pages.forEach((p,i)=>{const b=document.createElement('button');b.innerHTML='<span>'+String(i+1).padStart(2,'0')+'</span>'+esc(p.dataset.title);b.onclick=()=>go(i);$('#nav').append(b)});
function go(i,hash=true){$('#editor').hidden=true;current=Math.max(0,Math.min(pages.length-1,i));pages.forEach((p,n)=>p.classList.toggle('active',n===current));[...$('#nav').children].forEach((b,n)=>{b.classList.toggle('active',n===current);b.setAttribute('aria-current',n===current?'page':'false')});$('#pageCount').textContent=String(current+1).padStart(2,'0')+' / '+pages.length;$('#pageBar').style.width=((current+1)/pages.length*100)+'%';$('#prevBtn').disabled=current===0;$('#nextBtn').disabled=current===pages.length-1;if(hash)history.replaceState(null,'','#view-'+pages[current].id);window.scrollTo(0,0)}
function hashGo(){const idx=pages.findIndex(p=>'#view-'+p.id===location.hash);go(idx<0?0:idx,false)}window.addEventListener('hashchange',hashGo);
$('#prevBtn').onclick=()=>go(current-1);$('#nextBtn').onclick=()=>go(current+1);$('#notesBtn').onclick=()=>{const on=document.body.classList.toggle('show-notes');$('#notesBtn').setAttribute('aria-pressed',on)};
async function full(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(e){toast('请使用浏览器全屏功能')}}$('#fullBtn').onclick=full;$('#printBtn').onclick=()=>{render();window.print()};
document.addEventListener('keydown',e=>{if(!$('#editor').hidden||/INPUT|TEXTAREA|SELECT|BUTTON/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(['ArrowRight','PageDown'].includes(e.key)){e.preventDefault();go(current+1)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(current-1)}else if(e.key.toLowerCase()==='n')$('#notesBtn').click();else if(e.key.toLowerCase()==='f')full()});
render();hashGo();
