'use strict';
const KEY='suntech-ecommerce-meeting-v1';
const STATUS=['待更新','未开始','进行中','待核验','已完成','受阻','暂缓'];
const CATEGORIES=['会前准备','客户经营','两店整合','渠道工具','会议跟进'];
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>globalThis.crypto?.randomUUID?.()||'r'+Date.now().toString(36)+Math.random().toString(36).slice(2);
const direction={id:'merger-direction',title:'确定两店整合方向',category:'两店整合',priority:'P0',owner:'',due:'',status:'已完成',evidence:'已确认：玄甲店铺作为主店，美安士店铺转移至玄甲店铺。',blocker:''};
const initialTasks=[
['会前准备','重做重点客户总表','列清客户经营模式、已有合作、机会依据、下一步动作和负责人。'],
['客户经营','准备熟悉客户的深入案例','建议每位业务员先选3个真实熟悉客户；材料可回查，推测单列。'],
['客户经营','完成一次针对性客户跟进','保存实际沟通内容、切入理由、客户反馈和后续动作。'],
['客户经营','梳理存量客户并确定优先级','形成潜力客户清单和研究进度；优先级有具体判断依据。'],
['两店整合','核实美安士转入玄甲的可行处理方式','确认客户、产品、历史记录、合同费用及平台限制，不假定评价或权重可直接转移。'],
['两店整合','备份美安士店铺相关业务资料','核对客户、询盘、产品、订单及售后资料的授权导出范围、完整性和保存位置。'],
['两店整合','落实客户承接与跟进负责人','建立客户对应和负责人清单；客户沟通与未完承诺有人继续负责。'],
['两店整合','整理产品并承接到玄甲店铺','建立SKU对应、去重和资料核对清单；确认适用上架规则后处理。'],
['两店整合','核对未完订单、回款与售后','逐项明确履约、付款、客户承诺及售后归口，不能因转移中断。'],
['两店整合','调整玄甲店铺推广与预算安排','在规则及费用确认后制定投流、关键词和产品推广调整方案。'],
['两店整合','完成转移验收并确认美安士后续处理','核对玄甲承接结果及遗留事项；关店或合同终止另行确认。'],
['渠道工具','盘点付费获客工具的实际使用与效果','核对账单周期、已用功能、有效线索、跟进和成交；提出继续或调整建议。'],
['渠道工具','准备一次自主开发客户演示','从公开来源寻找目标客户，展示筛选依据、研究和具体沟通切入点。'],
['渠道工具','让同事共同使用Accio Work完成任务','用真实客户或运营任务演示，另一位同事能独立复现并解释检查方法。'],
['会前准备','核对上次安排的完成情况','逐项补充状态、负责人、完成依据或卡点，不把待更新当作未完成。'],
['会议跟进','把本次决定转成下一步动作','每项行动列负责人、期限、成果及需要的协助。'],
['会议跟进','复盘任务推进与客户反馈','下次先核对前次行动、客户反应、整合进度及待决定事项。']
];
function seed(){return {version:1,tasks:[{...direction},...initialTasks.map((r,i)=>({id:'task-'+(i+1),category:r[0],title:r[1],criteria:r[2],priority:i<11?'P0':'P1',owner:'',due:'',status:'待更新',evidence:'',blocker:''}))],customers:[],channels:[],minutes:{focus:'',decisions:'',support:'',next:''}}}
let toastTimer;function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,3500)}
let storageOK=true;
function text(v,max=6000){if(typeof v!=='string')return '';return v.slice(0,max)}
function date(v){if(!v)return '';if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v+'T00:00:00Z'))||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)throw Error('日期格式不正确');return v}
function numeric(v,integer=false){if(v===null||v===undefined||v==='')return null;const n=Number(v);if(!Number.isFinite(n)||n<0||(integer&&!Number.isInteger(n)))throw Error('金额和数量必须为有效非负数');return n}
function validate(raw){
 if(!raw||raw.version!==1||!Array.isArray(raw.tasks)||!Array.isArray(raw.customers)||!Array.isArray(raw.channels))throw Error('文件不是此工作台导出的数据');
 if([raw.tasks,raw.customers,raw.channels].some(a=>a.length>500))throw Error('记录数量超过上限');
 const s={version:1,tasks:[],customers:[],channels:[],minutes:{}};
 const seen=new Set();const getId=v=>{const k=text(v,120);if(!k||seen.has(k))throw Error('记录编号缺失或重复');seen.add(k);return k};
 s.tasks=raw.tasks.map(t=>{if(!t||typeof t!=='object')throw Error('待办格式不正确');const k=getId(t.id);if(k===direction.id)return {...direction,owner:text(t.owner,100)};if(!CATEGORIES.includes(t.category)||!STATUS.includes(t.status)||!['P0','P1','P2'].includes(t.priority)||!text(t.title,200).trim())throw Error('待办内容或状态不正确');if(t.status==='已完成'&&!text(t.evidence).trim())throw Error('已完成事项需要完成依据');return {id:k,title:text(t.title,200),category:t.category,priority:t.priority,owner:text(t.owner,100),due:date(t.due),status:t.status,criteria:text(t.criteria),evidence:text(t.evidence),blocker:text(t.blocker)}});
 if(!s.tasks.some(t=>t.id===direction.id))s.tasks.unshift({...direction});
 const customerKeys=['name','country','website','owner','model','cooperation','opportunity','action','feedback','next'];
 s.customers=raw.customers.map(r=>{if(!r||!text(r.name,160).trim())throw Error('客户名称缺失');const c={id:getId(r.id),due:date(r.due)};customerKeys.forEach(k=>c[k]=text(r[k],['name','country','website','owner'].includes(k)?300:6000));return c});
 s.channels=raw.channels.map(r=>{if(!r||!text(r.name,160).trim())throw Error('渠道名称缺失');const c={id:getId(r.id),name:text(r.name,160),period:text(r.period,160),currency:['CNY','USD','EUR'].includes(r.currency)?r.currency:'CNY',spend:numeric(r.spend),leads:numeric(r.leads,true),quotes:numeric(r.quotes,true),deals:numeric(r.deals,true),usage:text(r.usage),evidence:text(r.evidence),recommendation:text(r.recommendation),owner:text(r.owner,100)};if([c.spend,c.leads,c.quotes,c.deals].some(v=>v!==null)&&!c.period.trim())throw Error('有渠道数据时必须填写统计期');return c});
 for(const k of ['focus','decisions','support','next'])s.minutes[k]=text(raw.minutes?.[k]);return s;
}
let state;
try{const saved=localStorage.getItem(KEY);state=saved?validate(JSON.parse(saved)):seed()}catch(e){state=seed();storageOK=false;$('#storageInfo').textContent='本地记录暂时无法读取，当前显示初始清单。请保留原数据并使用导入恢复，新的修改可导出备份。'}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true;$('#saveStatus').textContent='已保存到当前浏览器'}catch(e){storageOK=false;$('#saveStatus').textContent='未能本地保存';$('#storageInfo').textContent='浏览器暂时无法保存修改，请使用“导出数据”保存文件，避免关闭后丢失。'} }
function today(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function overdue(t){return t.due&&t.due<today()&&!['已完成','暂缓'].includes(t.status)}
function badge(t){const c=t==='已完成'?'done':t==='受阻'?'blocked':['待更新','待核验'].includes(t)?'pending':'';return `<span class="badge ${c}">${esc(t)}</span>`}
function stats(target){const ts=state.tasks,done=ts.filter(t=>t.status==='已完成').length,active=ts.filter(t=>['进行中','待核验'].includes(t.status)).length,unknown=ts.filter(t=>t.status==='待更新').length,stuck=ts.filter(t=>t.status==='受阻').length;$(target).innerHTML=[['全部待办',ts.length,''],['已完成',done,Math.round(done/ts.length*100)+'% 已确认完成'],['推进中 / 待核验',active,''],['待更新',unknown,'实际进度待补充'],['受阻',stuck,ts.filter(overdue).length+' 项期限已过']].map(([label,n,extra])=>`<div class="stat"><span>${label}</span><strong>${n}</strong><small>${extra||'&nbsp;'}</small></div>`).join('')}
function taskTable(tasks){if(!tasks.length)return '<div class="empty">没有符合条件的事项。</div>';return '<div class="table-wrap"><table><thead><tr><th>待办与完成标准</th><th>责任 / 期限</th><th>状态</th><th>完成依据 / 当前卡点</th><th>操作</th></tr></thead><tbody>'+tasks.map(t=>`<tr><td><span class="task-title">${esc(t.title)}</span><small>${esc(t.category)} · ${esc(t.priority)}</small>${t.criteria?'<small>'+esc(t.criteria)+'</small>':''}</td><td>${esc(t.owner||'待指定')}<small>${esc(t.due||'待定期限')}</small>${overdue(t)?'<span class="overdue">期限已过，请核对状态</span>':''}</td><td>${badge(t.status)}</td><td class="evidence">${esc(t.evidence||'尚未填写完成依据')}${t.blocker?'<small class="error-text">卡点：'+esc(t.blocker)+'</small>':''}</td><td>${t.id===direction.id?'<span class="muted">方向已确定</span>':`<button data-edit="task" data-id="${esc(t.id)}">更新</button>`}</td></tr>`).join('')+'</tbody></table></div>'}
function renderTasks(){const q=$('#taskSearch').value.trim().toLowerCase(),cat=$('#categoryFilter').value,status=$('#statusFilter').value;const list=state.tasks.filter(t=>(!cat||t.category===cat)&&(!status||t.status===status)&&(!q||[t.title,t.owner,t.criteria,t.evidence,t.blocker].join(' ').toLowerCase().includes(q)));$('#taskTable').innerHTML=taskTable(list);const merger=state.tasks.filter(t=>t.category==='两店整合');$('#mergerTable').innerHTML=taskTable(merger);$('#mergerCount').textContent=`已完成 ${merger.filter(t=>t.status==='已完成').length} / ${merger.length} 项`;$('#nextTasks').innerHTML=taskTable(state.tasks.filter(t=>t.status!=='已完成'&&t.status!=='暂缓').sort((a,b)=>a.priority.localeCompare(b.priority)).slice(0,6));stats('#overviewStats');stats('#taskStats')}
function fact(label,value){return `<div><h3>${label}</h3><p>${esc(value||'待补充')}</p></div>`}
function renderCustomers(){$('#customerList').innerHTML=state.customers.length?state.customers.map(c=>`<article class="card customer-card"><div class="record-head"><div style="flex:1"><h2>${esc(c.name)}</h2><div class="record-meta">${esc(c.country||'国家待补')} · 负责人 ${esc(c.owner||'待指定')} · 下次跟进 ${esc(c.due||'待定')}</div><div class="record-meta">${esc(c.website||'官网 / 来源待补充')}</div></div><button data-edit="customer" data-id="${esc(c.id)}">编辑案例</button></div><div class="record-grid">${fact('客户经营与服务对象',c.model)}${fact('现有合作',c.cooperation)}${fact('合作机会与依据',c.opportunity)}${fact('已执行的动作',c.action)}${fact('客户反馈',c.feedback)}${fact('下一步与需要的支持',c.next)}</div></article>`).join(''):'<div class="empty">尚未添加客户案例。添加真实客户后，可在会上逐个展示经营判断、证据和推进动作。</div>'}
function metric(n){return n===null?'待补':n.toLocaleString('zh-CN',{maximumFractionDigits:2})}
function renderChannels(){$('#channelList').innerHTML=state.channels.length?state.channels.map(c=>{const cpl=c.spend!==null&&c.leads!==null?(c.leads>0?(c.spend/c.leads).toLocaleString('zh-CN',{maximumFractionDigits:2})+' '+c.currency:'有效线索为0，暂不计算'):'数据待补';return `<article class="card customer-card"><div class="record-head"><div style="flex:1"><h2>${esc(c.name)}</h2><div class="record-meta">${esc(c.period||'统计期待补充')} · 负责人 ${esc(c.owner||'待指定')}</div></div><button data-edit="channel" data-id="${esc(c.id)}">更新复盘</button></div><div class="metric-row"><span>投入 <b>${metric(c.spend)} ${esc(c.currency)}</b></span><span>有效线索 <b>${metric(c.leads)}</b></span><span>报价客户 <b>${metric(c.quotes)}</b></span><span>成交客户 <b>${metric(c.deals)}</b></span><span>有效线索成本 <b>${esc(cpl)}</b></span></div><div class="record-grid">${fact('实际使用与效果',c.usage)}${fact('数据来源及统计口径',c.evidence)}${fact('调整建议与下一步',c.recommendation)}</div></article>`}).join(''):'<div class="empty">添加实际使用的渠道或付费工具，例如国际站推广、已购获客服务、自主开发渠道。金额与结果请按真实记录填写。</div>'}
function render(){renderTasks();renderCustomers();renderChannels();for(const el of document.querySelectorAll('[data-minute]'))if(document.activeElement!==el)el.value=state.minutes[el.dataset.minute]}
$('#categoryFilter').innerHTML='<option value="">全部分类</option>'+CATEGORIES.map(c=>`<option>${c}</option>`).join('');$('#statusFilter').innerHTML='<option value="">全部状态</option>'+STATUS.map(c=>`<option>${c}</option>`).join('');$('#taskSearch').oninput=renderTasks;$('#categoryFilter').onchange=renderTasks;$('#statusFilter').onchange=renderTasks;

let editing=null;
const field=(name,label,value='',opts={})=>`<label class="${opts.wide?'wide':''}">${label}${opts.area?`<textarea name="${name}" maxlength="6000" ${opts.required?'required':''}>${esc(value)}</textarea>`:opts.options?`<select name="${name}">${opts.options.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`:`<input name="${name}" type="${opts.type||'text'}" value="${esc(value??'')}" ${opts.type==='number'?'min="0" step="'+(opts.integer?'1':'any')+'"':'maxlength="300"'} ${opts.required?'required':''}>`}</label>`;
function openEditor(kind,recordId){const arr=state[kind==='task'?'tasks':kind==='customer'?'customers':'channels'];const r=arr.find(x=>x.id===recordId)||{};if(r.id===direction.id)return;editing={kind,id:r.id||null};$('#editorTitle').textContent=(r.id?'编辑':'新增')+({task:'待办事项',customer:'客户案例',channel:'渠道复盘'}[kind]);let html='';
 if(kind==='task')html=field('title','事项名称',r.title,{wide:true,required:true})+field('category','分类',r.category||'会议跟进',{options:CATEGORIES})+field('priority','优先级',r.priority||'P1',{options:['P0','P1','P2']})+field('owner','负责人',r.owner)+field('due','截止日期',r.due,{type:'date'})+field('status','实际状态',r.status||'待更新',{options:STATUS})+'<div class="hint">P0为优先处理。未确认实际进度时保留“待更新”。</div>'+field('criteria','完成标准',r.criteria,{area:true,wide:true})+field('evidence','完成依据 / 当前进展（标为已完成时必填）',r.evidence,{area:true,wide:true})+field('blocker','卡点与需要的协助',r.blocker,{area:true,wide:true});
 if(kind==='customer')html=field('name','客户名称',r.name,{required:true})+field('country','国家 / 地区',r.country)+field('website','官网或资料来源',r.website,{wide:true})+field('owner','负责人',r.owner)+field('due','下次跟进日期',r.due,{type:'date'})+field('model','客户如何经营、卖给谁',r.model,{area:true,wide:true})+field('cooperation','现有合作与原因',r.cooperation,{area:true,wide:true})+field('opportunity','合作机会、依据和待验证判断',r.opportunity,{area:true,wide:true})+field('action','实际执行了什么',r.action,{area:true,wide:true})+field('feedback','客户反馈',r.feedback,{area:true,wide:true})+field('next','下一步与需要的支持',r.next,{area:true,wide:true});
 if(kind==='channel')html=field('name','渠道 / 工具名称',r.name,{required:true})+field('period','统计期',r.period)+field('currency','币种',r.currency||'CNY',{options:['CNY','USD','EUR']})+field('spend','投入金额（未知留空）',r.spend,{type:'number'})+field('leads','有效线索数（未知留空）',r.leads,{type:'number',integer:true})+field('quotes','报价客户数',r.quotes,{type:'number',integer:true})+field('deals','成交客户数',r.deals,{type:'number',integer:true})+field('owner','负责人',r.owner)+field('usage','已用功能、频次与实际产出',r.usage,{area:true,wide:true})+field('evidence','数据来源与有效线索定义',r.evidence,{area:true,wide:true})+field('recommendation','继续 / 调整 / 暂停的建议及下一步',r.recommendation,{area:true,wide:true});
 $('#editorFields').innerHTML='<div class="fields">'+html+'</div>';$('#deleteRecord').hidden=!r.id;$('#editor').showModal();}
$('#closeEditor').onclick=$('#cancelEditor').onclick=()=>$('#editor').close();
$('#editorForm').onsubmit=e=>{e.preventDefault();try{const r=Object.fromEntries(new FormData(e.target));r.id=editing.id||id();const key=editing.kind==='task'?'tasks':editing.kind==='customer'?'customers':'channels';if(editing.kind==='task'&&r.status==='已完成'&&!r.evidence.trim()){toast('请填写完成依据，再标记已完成。');return}const copy=JSON.parse(JSON.stringify(state));const idx=copy[key].findIndex(t=>t.id===r.id);if(idx>=0)copy[key][idx]=r;else copy[key].push(r);state=validate(copy);save();render();$('#editor').close();toast(storageOK?'已保存':'已更新，请导出备份')}catch(err){toast(err.message)}};
$('#deleteRecord').onclick=()=>{if(!editing?.id||!confirm('确定删除这条记录？删除前可先导出备份。'))return;const key=editing.kind==='task'?'tasks':editing.kind==='customer'?'customers':'channels';state[key]=state[key].filter(r=>r.id!==editing.id);save();render();$('#editor').close();toast('已删除记录')};
document.addEventListener('click',e=>{const b=e.target.closest('[data-edit]');if(b)openEditor(b.dataset.edit,b.dataset.id);const g=e.target.closest('[data-go]');if(g)go(pages.findIndex(p=>p.id===g.dataset.go))});
$('#addTask').onclick=$('#addTaskFromMinutes').onclick=()=>openEditor('task');$('#addCustomer').onclick=()=>openEditor('customer');$('#addChannel').onclick=()=>openEditor('channel');
document.querySelectorAll('[data-minute]').forEach(el=>el.oninput=()=>{state.minutes[el.dataset.minute]=el.value.slice(0,6000);save()});

function download(content,type,filename){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#exportBtn').onclick=()=>download(JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2),'application/json','电商会议数据-'+today()+'.json');
$('#importBtn').onclick=()=>$('#importFile').click();
$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>4*1024*1024)throw Error('文件过大，请选择本工作台导出的JSON文件');const incoming=validate(JSON.parse(await f.text()));if(!confirm(`导入将替换当前浏览器记录（${incoming.tasks.length}项待办、${incoming.customers.length}个客户、${incoming.channels.length}项渠道）。建议先导出当前数据。确定导入？`))return;state=incoming;save();render();toast('已导入数据')}catch(err){toast('导入失败：'+err.message)}finally{e.target.value=''}};
$('#downloadMinutes').onclick=()=>{let md='# 电商部会议记录\n\n两店整合方向：玄甲店铺作为主店，美安士店铺转移至玄甲店铺。\n\n';for(const [k,label] of [['focus','讨论重点'],['decisions','已确认决定'],['support','需要协调或决定'],['next','下次检查']])md+='## '+label+'\n\n'+(state.minutes[k]||'待补充')+'\n\n';md+='## 待办情况\n\n';for(const t of state.tasks)md+=`- [${t.status==='已完成'?'x':' '}] ${t.title}（${t.status}；负责人：${t.owner||'待指定'}；期限：${t.due||'待定'}）\n  完成依据：${t.evidence||'待补充'}\n${t.blocker?'  卡点：'+t.blocker+'\n':''}`;md+='\n## 客户案例\n\n';for(const c of state.customers)md+=`### ${c.name}\n\n负责人：${c.owner||'待指定'}\n\n经营：${c.model}\n\n合作：${c.cooperation}\n\n机会与依据：${c.opportunity}\n\n动作：${c.action}\n\n反馈：${c.feedback}\n\n下一步：${c.next}\n\n`;download(md,'text/markdown;charset=utf-8','电商部会议纪要-'+today()+'.md')};
const pages=[...document.querySelectorAll('.page')];let current=0;
pages.forEach((p,i)=>{const b=document.createElement('button');b.innerHTML='<span>'+String(i+1).padStart(2,'0')+'</span>'+esc(p.dataset.title);b.onclick=()=>go(i);$('#nav').append(b)});
function go(i,hash=true){current=Math.max(0,Math.min(pages.length-1,i));pages.forEach((p,n)=>p.classList.toggle('active',n===current));[...$('#nav').children].forEach((b,n)=>{b.classList.toggle('active',n===current);b.setAttribute('aria-current',n===current?'page':'false')});$('#pageCount').textContent=String(current+1).padStart(2,'0')+' / '+pages.length;$('#pageBar').style.width=((current+1)/pages.length*100)+'%';$('#prevBtn').disabled=current===0;$('#nextBtn').disabled=current===pages.length-1;if(hash)history.replaceState(null,'','#view-'+pages[current].id);window.scrollTo(0,0)}
function hashGo(){const idx=pages.findIndex(p=>'#view-'+p.id===location.hash);go(idx<0?0:idx,false)}window.addEventListener('hashchange',hashGo);
$('#prevBtn').onclick=()=>go(current-1);$('#nextBtn').onclick=()=>go(current+1);$('#notesBtn').onclick=()=>{const on=document.body.classList.toggle('show-notes');$('#notesBtn').setAttribute('aria-pressed',on)};
async function full(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(e){toast('请使用浏览器全屏功能')}}$('#fullBtn').onclick=full;$('#printBtn').onclick=()=>{render();window.print()};
document.addEventListener('keydown',e=>{if($('#editor').open||/INPUT|TEXTAREA|SELECT|BUTTON/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(['ArrowRight','PageDown'].includes(e.key)){e.preventDefault();go(current+1)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(current-1)}else if(e.key.toLowerCase()==='n')$('#notesBtn').click();else if(e.key.toLowerCase()==='f')full()});
render();hashGo();
